return {
	'sainnhe/gruvbox-material',
	config = function()
		vim.cmd('colorscheme gruvbox-material')
		Clr('Normal', {ctermbg='none'})
		Clr('NormalFloat', {ctermbg='none'})
		Clr('NormalNC', {ctermbg='none'})
		Clr('EndOfBuffer', {ctermfg=8 ,ctermbg='none'})
		Clr('Visual', {ctermbg=240})
		Clr('MatchParen', {ctermfg=46, ctermbg='none', bold=true})
		Clr('Whitespace', {ctermfg=8})
		Clr('CursorColumn', {ctermbg=238})
		Clr('CursorLine', {ctermbg=238})
		Clr('CursorLineNr', {ctermfg=254})
		Clr('CursorLineFold', {ctermfg=12, bold=true})
		Clr('LineNr', {ctermfg=246})
		Clr('Folded', {ctermfg=4, ctermbg=0})
		Clr('TabLine', {ctermfg=1, ctermbg=1})
		Clr('TabLineFill', {ctermbg=0})
		Clr('FloatBorder', {ctermbg=0})
		Clr('FloatTitle', {ctermfg=5, ctermbg=0})
		Clr('AZ', {ctermfg=0, ctermbg=4, bold=true})
		Clr('VE', {ctermfg=0, ctermbg=2, bold=true})
		Clr('AM', {ctermfg=0, ctermbg=3, bold=true})
		Clr('RO', {ctermfg=0, ctermbg=1, bold=true})
		Clr('MA', {ctermfg=0, ctermbg=5, bold=true})
		Clr('CI', {ctermfg=0, ctermbg=6, bold=true})
	end
}
